export const caldecotte = {
  id: "caldecotte-lake",
  name: "Caldecotte Lake",
  width: 40,
  height: 28,
  defaultSpawn: "start",
  spawns: {
    start: {
      x: 21 * 32,
      y: 20 * 32,
      direction: "up",
    },
  },
  exits: [
    {
      x: 19,
      y: 1,
      width: 2,
      height: 1,
      targetMap: "test-field",
      targetSpawn: "start",
      requiresFlag: "route_1_unlocked",
      lockedMessage: "The route away from Caldecotte is not open yet.",
    },
  ],
  npcs: [
    {
      id: "coach-tim-caldecotte",
      name: "Coach Tim",
      x: 21,
      y: 17,
      width: 1,
      height: 1,
      dialogueId: "coachTimCaldecotte",
      color: "npc",
    },
    {
      id: "lesley-caldecotte",
      name: "Lesley",
      x: 10,
      y: 17,
      width: 1,
      height: 1,
      dialogueId: "lesleyCaldecotte",
      color: "npcAlt",
    },
    {
      id: "marcus-caldecotte",
      name: "Marcus",
      x: 29,
      y: 22,
      width: 1,
      height: 1,
      dialogueId: "marcusCaldecotte",
      color: "npcAlt",
    },
    {
      id: "dan-caldecotte",
      name: "Dan",
      x: 15,
      y: 6,
      width: 1,
      height: 1,
      dialogueId: "danCaldecotte",
      color: "npcAlt",
    },
    {
      id: "naomi-caldecotte",
      name: "Naomi",
      x: 27,
      y: 5,
      width: 1,
      height: 1,
      dialogueId: "naomiCaldecotte",
      color: "npcAlt",
    },
    {
      id: "noticeboard-member-caldecotte",
      name: "Club Member",
      x: 12,
      y: 13,
      width: 1,
      height: 1,
      dialogueId: "noticeboardMemberCaldecotte",
      color: "npc",
    },
    {
      id: "spectator-caldecotte",
      name: "Spectator",
      x: 25,
      y: 20,
      width: 1,
      height: 1,
      dialogueId: "spectatorCaldecotte",
      color: "npc",
    },
    {
      id: "junior-paddler-caldecotte",
      name: "Junior Paddler",
      x: 17,
      y: 11,
      width: 1,
      height: 1,
      dialogueId: "juniorPaddlerCaldecotte",
      color: "npc",
    },
  ],
  tiles: [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGPPGGGGGGGGGGGWWWWWWWWW",
    "WGGTTTGGGGGGGGGGGGPPGGGGCCCCCCGWWWWWWWWW",
    "WGGTTTGGGGGGGGGGGGPPGGGGCCCCCCGWWWWWWWWW",
    "WGGGGGGGGGGGGGRRRGGPPGGGCCCCCCGWWWWWWWWW",
    "WGGGGGGGGGGGGGRRRGGPPGGGGGGGGGGWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGWWWWWWWWW",
    "WGGGGGGGGGGGSGGGGGGPPGGGGGGGGGGWWWWWWWWW",
    "WPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGWWWWWWWWW",
    "WPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGWWWWWWWWW",
    "WGGGBBBBBBGGGGGGGGGPPGGGGGGGGGGWWWWWWWWW",
    "WGGGBBBBBBGGGGGGGGGPPGGGGGGGGGGWWWWWWWWW",
    "WGGGBBBBBBGGGGGGGGGPPGGGGGGGGGGWWWWWWWWW",
    "WGGGBBBBBBGGGGGGGGGPPGGGGGGGGGGWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGPPGGGGGKKKKKWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGPPGGGGGKKKKKWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGPPGGGGGKKKKKWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGPPGGGGGGGGGGWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
  ],
  solidTiles: ["W", "T", "B", "S", "R"],
};
