export const trainingYard = {
  id: "training-yard",
  name: "Training Yard",
  width: 28,
  height: 20,
  defaultSpawn: "fromTestField",
  spawns: {
    fromTestField: {
      x: 3 * 32,
      y: 10 * 32,
      direction: "right",
    },
  },
  exits: [
    {
      x: 1,
      y: 9,
      width: 1,
      height: 3,
      targetMap: "test-field",
      targetSpawn: "fromTrainingYard",
    },
  ],
  npcs: [
    {
      id: "yard-paddler-test",
      name: "Training Paddler",
      x: 14,
      y: 10,
      width: 1,
      height: 1,
      dialogueId: "trainingPaddlerTest",
      color: "npc",
    },
  ],
  tiles: [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WGGGGGGGGGGGGGGGGGGGGGGGGGGW",
    "WGGGGGGGGGGGGGGGGGGGGGGGGGGW",
    "WGGGTTTGGGGGGGGGGGGGGGTTTGGW",
    "WGGGTTTGGGGGGGGGGGGGGGTTTGGW",
    "WGGGGGGGGGGGGGGGGGGGGGGGGGGW",
    "WGGGGGGGGGGGGGGGGGGGGGGGGGGW",
    "WGGGGGGPPPPPPPPPPPPPPGGGGGGW",
    "WGGGGGGPPPPPPPPPPPPPPGGGGGGW",
    "WGGGGGGPPGGGGGGGGGGPPGGGGGGW",
    "WGGGGGGPPGGGGGGGGGGPPGGGGGGW",
    "WGGGGGGPPGGGGGGGGGGPPGGGGGGW",
    "WGGGGGGPPPPPPPPPPPPPPGGGGGGW",
    "WGGGGGGPPPPPPPPPPPPPPGGGGGGW",
    "WGGGGGGGGGGGGGGGGGGGGGGGGGGW",
    "WGGGGGGGGGGGGDDDDGGGGGGGGGGW",
    "WGGGGGGGGGGGGDDDDGGGGGGGGGGW",
    "WGGGGGGGGGGGGGGGGGGGGGGGGGGW",
    "WGGGGGGGGGGGGGGGGGGGGGGGGGGW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
  ],
  solidTiles: ["W", "T", "D"],
};
